/**
 * ═══════════════════════════════════════════════════════════════════════════
 * 📌 ملخص توجيهي | Guiding Summary
 * ═══════════════════════════════════════════════════════════════════════════
 * 🎯 المهمة: منظومة الأدوات الموحدة - Unified Tools System
 * 🏛️ الدور: مصدر حقيقة شامل - تعريفات مركزية لكل الأدوات في المحررات الأربعة
 * 📥 المستهلك: ToolRegistry, SharedRibbonBar, UnifiedToolboxBlock, كل المحررات
 * ═══════════════════════════════════════════════════════════════════════════
 * 🧠 الطريقة المبتكرة | Innovative Pattern:
 *    Centralized Tool Definitions: تعريفات مركزية لأدوات التنسيق والويب والأشكال
 *    والمخططات والمستندات مع صفر تكرار
 * ═══════════════════════════════════════════════════════════════════════════
 * ⚠️ نقاط الخطر الإلزامية | Mandatory Gotchas:
 *    1. 23 نوع أداة ويب تدفقية يجب تسجيلها
 *    2. الأشكال الفيكتورية يجب أن تظهر في كل المحررات
 *    3. IDs يجب أن تكون فريدة
 * ═══════════════════════════════════════════════════════════════════════════
 * 🩹 البرمجة الدفاعية | Defensive Coding:
 *    - فحص عدم تكرار IDs
 *    - إرجاع مصفوفة فارغة عند الخطأ
 *    - تحديث هذا الملف عند إضافة أداة جديدة
 * ═══════════════════════════════════════════════════════════════════════════
 * ©️ جميع الحقوق محفوظة ©️ - 2026
 * (يُحظر التعديل على هذا الملف دون تحديث هذا السجل)
 * ═══════════════════════════════════════════════════════════════════════════
 */

export type ToolCategory =
  | 'formatting'
  | 'flow-elements'
  | 'vector-shapes'
  | 'diagrams-math'
  | 'latex-scientific'
  | 'media-callouts'
  | 'document-io'
  | 'viewport-view'
  | 'history-edit'
  | 'computational-calc'
  | 'developer';

export interface UnifiedToolItem {
  id: string;
  titleAr: string;
  titleEn: string;
  category: ToolCategory;
  categoryAr: string;
  iconName: string;
  shortcut?: string;
  descriptionAr: string;
  actionId: string;
  payload?: Record<string, any>;
  keywords: string[];
}

export const UNIFIED_TOOL_ITEMS: UnifiedToolItem[] = [
  // 1. Text & Rich Formatting
  {
    id: 'tool-format-bold',
    titleAr: 'خط عريض',
    titleEn: 'Bold',
    category: 'formatting',
    categoryAr: 'تنسيق النصوص',
    iconName: 'Bold',
    shortcut: 'Ctrl+B',
    descriptionAr: 'تطبيق النمط العريض على النص المحدد',
    actionId: 'format:bold',
    keywords: ['bold', 'عريض', 'تغميق', 'خط', 'نص'],
  },
  {
    id: 'tool-format-italic',
    titleAr: 'خط مائل',
    titleEn: 'Italic',
    category: 'formatting',
    categoryAr: 'تنسيق النصوص',
    iconName: 'Italic',
    shortcut: 'Ctrl+I',
    descriptionAr: 'إمالة النص المحدد',
    actionId: 'format:italic',
    keywords: ['italic', 'مائل', 'خط'],
  },
  {
    id: 'tool-format-underline',
    titleAr: 'تسطير سفلي',
    titleEn: 'Underline',
    category: 'formatting',
    categoryAr: 'تنسيق النصوص',
    iconName: 'Underline',
    shortcut: 'Ctrl+U',
    descriptionAr: 'وضع خط أسفل النص المحدد',
    actionId: 'format:underline',
    keywords: ['underline', 'تسطير', 'خط سفلي'],
  },
  {
    id: 'tool-align-right',
    titleAr: 'محاذاة لليمين',
    titleEn: 'Align Right',
    category: 'formatting',
    categoryAr: 'تنسيق النصوص',
    iconName: 'AlignRight',
    descriptionAr: 'محاذاة النص والفقرة إلى اليمين (RTL)',
    actionId: 'format:align-right',
    keywords: ['right', 'يمين', 'محاذاة'],
  },
  {
    id: 'tool-align-center',
    titleAr: 'محاذاة للوسط',
    titleEn: 'Align Center',
    category: 'formatting',
    categoryAr: 'تنسيق النصوص',
    iconName: 'AlignCenter',
    descriptionAr: 'توسيط النص والكتل',
    actionId: 'format:align-center',
    keywords: ['center', 'وسط', 'توسيط'],
  },
  {
    id: 'tool-align-left',
    titleAr: 'محاذاة لليسار',
    titleEn: 'Align Left',
    category: 'formatting',
    categoryAr: 'تنسيق النصوص',
    iconName: 'AlignLeft',
    descriptionAr: 'محاذاة النص إلى اليسار (LTR)',
    actionId: 'format:align-left',
    keywords: ['left', 'يسار', 'محاذاة'],
  },

  // 2. 23 Flow & Web Layout Elements (الكتل التدفقية)
  {
    id: 'tool-flow-section',
    titleAr: 'قسم تدفقي (Section)',
    titleEn: 'Flow Section',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Layout',
    descriptionAr: 'حاوية قسم رئيسي بعرض كامل أو مقيد',
    actionId: 'canvas:add-element',
    payload: { type: 'section' },
    keywords: ['section', 'قسم', 'سكشن', 'تدفق', 'كتلة'],
  },
  {
    id: 'tool-flow-container',
    titleAr: 'حاوية كتل (Container)',
    titleEn: 'Container Box',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Square',
    descriptionAr: 'حاوية ضبط العرض الداخلي والهوامش',
    actionId: 'canvas:add-element',
    payload: { type: 'container' },
    keywords: ['container', 'حاوية', 'صندوق'],
  },
  {
    id: 'tool-flow-grid',
    titleAr: 'شبكة أعمدة (12-Grid)',
    titleEn: '12-Column Grid',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Grid',
    descriptionAr: 'شبكة تخطيط تدفقية قابلة لتغيير عرض الأعمدة بالفأرة',
    actionId: 'canvas:add-element',
    payload: { type: 'grid' },
    keywords: ['grid', 'شبكة', 'أعمدة', '12'],
  },
  {
    id: 'tool-flow-navbar',
    titleAr: 'شريط ترويسة وتنقل (Navbar)',
    titleEn: 'Navigation Bar',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Navigation',
    descriptionAr: 'ترويسة متكاملة مع الشعار والروابط وزر الإجراء',
    actionId: 'canvas:add-element',
    payload: { type: 'navbar' },
    keywords: ['navbar', 'قائمة', 'ترويسة', 'نافيجيشن'],
  },
  {
    id: 'tool-flow-hero',
    titleAr: 'قسم ترحيبي عريض (Hero)',
    titleEn: 'Hero Header',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Sparkles',
    descriptionAr: 'عنوان رئيسي مع شارة ووصف وزري إجراء',
    actionId: 'canvas:add-element',
    payload: { type: 'hero' },
    keywords: ['hero', 'هيرو', 'ترحيب', 'بطولة'],
  },
  {
    id: 'tool-flow-features',
    titleAr: 'شبكة ميزات (Features)',
    titleEn: 'Features Grid',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Layers',
    descriptionAr: 'بطاقات عرض الميزات والخدمات',
    actionId: 'canvas:add-element',
    payload: { type: 'features' },
    keywords: ['features', 'ميزات', 'خدمات', 'بينتو'],
  },
  {
    id: 'tool-flow-pricing',
    titleAr: 'جدول أسعار وباقات (Pricing)',
    titleEn: 'Pricing Table',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'CreditCard',
    descriptionAr: 'بطاقات باقات الاشتراك وخيارات الدفع',
    actionId: 'canvas:add-element',
    payload: { type: 'pricing' },
    keywords: ['pricing', 'أسعار', 'باقات', 'اشتراك'],
  },
  {
    id: 'tool-flow-testimonials',
    titleAr: 'آراء العملاء (Testimonials)',
    titleEn: 'Testimonials',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Quote',
    descriptionAr: 'شهادات وتقييمات العملاء والشركاء',
    actionId: 'canvas:add-element',
    payload: { type: 'testimonials' },
    keywords: ['testimonials', 'آراء', 'تقييمات', 'شهادات'],
  },
  {
    id: 'tool-flow-faq',
    titleAr: 'الأسئلة الشائعة (FAQ Accordion)',
    titleEn: 'FAQ Accordion',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'HelpCircle',
    descriptionAr: 'قوائم أكورديون قابلة للفتح والغلق بالفأرة',
    actionId: 'canvas:add-element',
    payload: { type: 'faq' },
    keywords: ['faq', 'أسئلة', 'شائعة', 'أكورديون'],
  },
  {
    id: 'tool-flow-cta',
    titleAr: 'دعوة لاتخاذ إجراء (Call to Action)',
    titleEn: 'CTA Banner',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'CheckCircle2',
    descriptionAr: 'بانر تشجيعي فاتح لجذب التفاعل',
    actionId: 'canvas:add-element',
    payload: { type: 'cta' },
    keywords: ['cta', 'دعوة', 'تسجيل', 'بانر'],
  },
  {
    id: 'tool-flow-footer',
    titleAr: 'تذييل الصفحة (Footer)',
    titleEn: 'Page Footer',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Layout',
    descriptionAr: 'تذييل سفلي يحتوي على روابط الموقع وحقوق النشر',
    actionId: 'canvas:add-element',
    payload: { type: 'footer' },
    keywords: ['footer', 'تذييل', 'فوتر', 'حقوق'],
  },
  {
    id: 'tool-flow-cms-list',
    titleAr: 'قائمة بيانات متكررة (CMS List)',
    titleEn: 'CMS Repeater List',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'ListFilter',
    descriptionAr: 'كتلة تكرار ديناميكية لعرض المقالات والمنتجات',
    actionId: 'canvas:add-element',
    payload: { type: 'cms-list' },
    keywords: ['cms', 'list', 'بيانات', 'تكرار', 'مجموعة'],
  },
  {
    id: 'tool-flow-form',
    titleAr: 'نموذج إدخال (Form Container)',
    titleEn: 'Form Container',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'CheckSquare',
    descriptionAr: 'حاوية استمارة مع أزرار الإرسال والتحقق',
    actionId: 'canvas:add-element',
    payload: { type: 'form' },
    keywords: ['form', 'نموذج', 'استمارة'],
  },
  {
    id: 'tool-flow-input',
    titleAr: 'حقل إدخال (Input Field)',
    titleEn: 'Input Field',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Type',
    descriptionAr: 'حقل نصي لإدخال البيانات',
    actionId: 'canvas:add-element',
    payload: { type: 'input' },
    keywords: ['input', 'حقل', 'إدخال'],
  },
  {
    id: 'tool-flow-heading',
    titleAr: 'عنوان نصي (Heading H1-H6)',
    titleEn: 'Heading Text',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Type',
    descriptionAr: 'عناوين رئيسية وفرعية بنمط طباعي متزن',
    actionId: 'canvas:add-element',
    payload: { type: 'heading' },
    keywords: ['heading', 'عنوان', 'نص عريض'],
  },
  {
    id: 'tool-flow-paragraph',
    titleAr: 'فقرة نصية (Paragraph)',
    titleEn: 'Paragraph',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Type',
    descriptionAr: 'كتلة نصية منضبطة التباعد والقراءة',
    actionId: 'canvas:add-element',
    payload: { type: 'paragraph' },
    keywords: ['paragraph', 'فقرة', 'نص'],
  },
  {
    id: 'tool-flow-button',
    titleAr: 'زر تفاعلي (Interactive Button)',
    titleEn: 'Action Button',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'CheckCircle2',
    descriptionAr: 'زر بتصميم فاتح أنيق مع تأثيرات الضغط والتمرير',
    actionId: 'canvas:add-element',
    payload: { type: 'button' },
    keywords: ['button', 'زر', 'إجراء'],
  },
  {
    id: 'tool-flow-badge',
    titleAr: 'شارة مميزة (Badge Tag)',
    titleEn: 'Badge Tag',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Sparkles',
    descriptionAr: 'وسم صغير لعرض الحالات والإعلانات',
    actionId: 'canvas:add-element',
    payload: { type: 'badge' },
    keywords: ['badge', 'شارة', 'وسم'],
  },
  {
    id: 'tool-flow-card',
    titleAr: 'بطاقة محتوى (Content Card)',
    titleEn: 'Content Card',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Square',
    descriptionAr: 'بطاقة ذات حدود رقيقة وظلال ناعمة خفيفة',
    actionId: 'canvas:add-element',
    payload: { type: 'card' },
    keywords: ['card', 'بطاقة', 'كرت'],
  },
  {
    id: 'tool-flow-divider',
    titleAr: 'فاصل أفقي (Divider Line)',
    titleEn: 'Divider Line',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Minus',
    descriptionAr: 'خط فاصل بصري ناعم بين الأقسام',
    actionId: 'canvas:add-element',
    payload: { type: 'divider' },
    keywords: ['divider', 'فاصل', 'خط'],
  },
  {
    id: 'tool-flow-video',
    titleAr: 'مشغل وسائط وفيديو (Video Player)',
    titleEn: 'Video Frame',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Video',
    descriptionAr: 'إطار مخصص لعرض المقاطع والعروض التوضيحية',
    actionId: 'canvas:add-element',
    payload: { type: 'video' },
    keywords: ['video', 'فيديو', 'وسائط', 'مشغل'],
  },

  // 2.2 Site Pages & Navigation Model Elements (إدارة وتخطيط صفحات الموقع النموذجية)
  {
    id: 'tool-flow-page-tree',
    titleAr: 'شجرة صفحات الموقع (Site Tree Map)',
    titleEn: 'Site Tree Map',
    category: 'flow-elements',
    categoryAr: 'صفحات الموقع والتنقل',
    iconName: 'FolderTree',
    descriptionAr: 'خريطة وهيكل شجري لصفحات الموقع وإدارتها بنقرة واحدة',
    actionId: 'canvas:add-element',
    payload: { type: 'page-tree' },
    keywords: ['page', 'pages', 'tree', 'صفحات', 'شجرة', 'موقع', 'هيكل'],
  },
  {
    id: 'tool-flow-navbar-tree',
    titleAr: 'شريط تنقل شجري متعدد الصفحات (Site Navbar)',
    titleEn: 'Site Multi-Page Navbar',
    category: 'flow-elements',
    categoryAr: 'صفحات الموقع والتنقل',
    iconName: 'Navigation',
    descriptionAr: 'شريط تنقل متصل بشجرة صفحات الموقع والروابط المباشرة',
    actionId: 'canvas:add-element',
    payload: { type: 'navbar-tree' },
    keywords: ['navbar', 'تنقل', 'روابط', 'صفحات', 'شريط'],
  },
  {
    id: 'tool-flow-breadcrumbs',
    titleAr: 'مسار التنقل التدرجي (Breadcrumbs Trail)',
    titleEn: 'Breadcrumbs Trail',
    category: 'flow-elements',
    categoryAr: 'صفحات الموقع والتنقل',
    iconName: 'Compass',
    descriptionAr: 'شريط مسار التنقل الدلالي الهرمي بين صفحات الموقع',
    actionId: 'canvas:add-element',
    payload: { type: 'breadcrumbs' },
    keywords: ['breadcrumbs', 'مسار', 'تدرج', 'تنقل', 'صفحة'],
  },
  {
    id: 'tool-flow-page-cards',
    titleAr: 'شبكة بطاقات الصفحات (Pages Bento Grid)',
    titleEn: 'Pages Bento Grid',
    category: 'flow-elements',
    categoryAr: 'صفحات الموقع والتنقل',
    iconName: 'Layout',
    descriptionAr: 'شبكة بطاقات بصرية لاستعراض صفحات الموقع وأقسامه',
    actionId: 'canvas:add-element',
    payload: { type: 'page-cards' },
    keywords: ['pages', 'cards', 'bento', 'بطاقات', 'صفحات'],
  },
  {
    id: 'tool-flow-page-settings',
    titleAr: 'إعدادات وميتا الصفحة (Page Meta Settings)',
    titleEn: 'Page Meta Settings',
    category: 'flow-elements',
    categoryAr: 'صفحات الموقع والتنقل',
    iconName: 'Sliders',
    descriptionAr: 'لوحة ضبط العنوان والـ Slug والكلمات المفتاحية والاتجاه',
    actionId: 'canvas:add-element',
    payload: { type: 'page-settings' },
    keywords: ['settings', 'meta', 'slug', 'إعدادات', 'عنوان', 'صفحة'],
  },

  // 2.3 Presentation Slides & Snippets (العروض التقديمية والشرائح النموذجية)
  {
    id: 'tool-flow-slide-hero',
    titleAr: 'شريحة عنوان وغلاف (Hero Slide)',
    titleEn: 'Hero Title Slide',
    category: 'flow-elements',
    categoryAr: 'العروض والشرائح التقديمية',
    iconName: 'Tv',
    descriptionAr: 'شريحة غلاف رئيسية للعرض التقديمي مع رأس وذيل وترقيم',
    actionId: 'canvas:add-element',
    payload: { type: 'slide-hero' },
    keywords: ['slide', 'presentation', 'hero', 'شريحة', 'عرض', 'غلاف'],
  },
  {
    id: 'tool-flow-slide-single',
    titleAr: 'شريحة محتوى أحادية (Single-Col Slide)',
    titleEn: 'Single-Column Slide',
    category: 'flow-elements',
    categoryAr: 'العروض والشرائح التقديمية',
    iconName: 'Presentation',
    descriptionAr: 'شريحة عرض نموذجية لموضوع رئيسي وفقرات تفصيلية',
    actionId: 'canvas:add-element',
    payload: { type: 'slide-single' },
    keywords: ['slide', 'single', 'شريحة', 'عمود', 'عرض'],
  },
  {
    id: 'tool-flow-slide-two-col',
    titleAr: 'شريحة مقارنة ثنائية (Two-Col Slide)',
    titleEn: 'Two-Column Slide',
    category: 'flow-elements',
    categoryAr: 'العروض والشرائح التقديمية',
    iconName: 'Columns',
    descriptionAr: 'شريحة عرض لتقسيم الأفكار ومقارنة المفاهيم جنبًا إلى جنب',
    actionId: 'canvas:add-element',
    payload: { type: 'slide-two-col' },
    keywords: ['slide', 'two-col', 'شريحة', 'مقارنة', 'عمودين'],
  },
  {
    id: 'tool-flow-slide-split-code',
    titleAr: 'شريحة شفرة وتنفيذ (Split Code Slide)',
    titleEn: 'Split Code Slide',
    category: 'flow-elements',
    categoryAr: 'العروض والشرائح التقديمية',
    iconName: 'Code2',
    descriptionAr: 'شريحة عرض للشفرات البرمجية مع صندوق المخرجات الحية',
    actionId: 'canvas:add-element',
    payload: { type: 'slide-split-code' },
    keywords: ['slide', 'code', 'شريحة', 'برمجة', 'كود'],
  },
  {
    id: 'tool-flow-slide-math',
    titleAr: 'شريحة نماذج ومعادلات (Math Slide)',
    titleEn: 'Math Science Slide',
    category: 'flow-elements',
    categoryAr: 'العروض والشرائح التقديمية',
    iconName: 'Sigma',
    descriptionAr: 'شريحة مصممة للصيغ الرياضية واقتباسات النظريات العلمية',
    actionId: 'canvas:add-element',
    payload: { type: 'slide-math' },
    keywords: ['slide', 'math', 'latex', 'شريحة', 'رياضيات', 'معادلات'],
  },
  {
    id: 'tool-flow-presenter-tip',
    titleAr: 'قصاصة تنبيه العارض (Presenter Tip)',
    titleEn: 'Presenter Tip Callout',
    category: 'flow-elements',
    categoryAr: 'العروض والشرائح التقديمية',
    iconName: 'StickyNote',
    descriptionAr: 'مربع تنبيه وتوجيه مخصص لملاحظات العارض والمحاضر',
    actionId: 'canvas:add-element',
    payload: { type: 'presenter-tip' },
    keywords: ['tip', 'callout', 'presenter', 'ملاحظة', 'عارض', 'تنبيه'],
  },

  // 3. Vector Shapes & Path Tools (الأشكال الفيكتورية ومحرك المسارات)
  {
    id: 'tool-vector-pen',
    titleAr: 'قلم فيكتوري حر (Pen Tool)',
    titleEn: 'Vector Pen Tool',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'PenTool',
    shortcut: 'P',
    descriptionAr: 'رسم منحنيات بيزييه ومسارات متجهة حرة بدقة عالية',
    actionId: 'canvas:select-tool',
    payload: { tool: 'pen' },
    keywords: ['pen', 'قلم', 'فيكتور', 'مسار', 'بيزييه'],
  },
  {
    id: 'tool-vector-path',
    titleAr: 'مسار بيزييه (Bezier Path)',
    titleEn: 'Bezier Path',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'Spline',
    descriptionAr: 'إدراج مسار منحني ناعم مع مقابض تحكم قابلة للتعديل',
    actionId: 'canvas:add-element',
    payload: { type: 'path' },
    keywords: ['path', 'spline', 'منحنى', 'بيزييه', 'مسار'],
  },
  {
    id: 'tool-vector-edit-points',
    titleAr: 'تحرير النقاط والمقابض (Direct Selection)',
    titleEn: 'Edit Path Points',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'Edit3',
    shortcut: 'A',
    descriptionAr: 'تعديل رؤوس المسارات الفيكتورية ومقابض بيزييه بالضغط والسحب',
    actionId: 'canvas:select-tool',
    payload: { tool: 'edit-points' },
    keywords: ['edit', 'points', 'vertices', 'نقاط', 'تحرير', 'مقابض'],
  },
  {
    id: 'tool-shape-polygon',
    titleAr: 'مضلع متعدد الأضلاع (Polygon)',
    titleEn: 'Regular Polygon',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'Hexagon',
    descriptionAr: 'رسم مضلع هندسي منتظم متعدد الرؤوس',
    actionId: 'canvas:add-element',
    payload: { type: 'polygon', sides: 6 },
    keywords: ['polygon', 'مضلع', 'أضلاع', 'سداسي', 'ثماني'],
  },
  {
    id: 'tool-shape-rectangle',
    titleAr: 'مستطيل / مربع',
    titleEn: 'Rectangle',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'Square',
    descriptionAr: 'رسم مستطيل أو بطاقة بحواف دائرية قابلة للتحكم',
    actionId: 'canvas:add-element',
    payload: { type: 'rectangle' },
    keywords: ['rectangle', 'مستطيل', 'مربع', 'شكل'],
  },
  {
    id: 'tool-shape-circle',
    titleAr: 'دائرة / شكل بيضاوي',
    titleEn: 'Circle',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'Circle',
    descriptionAr: 'رسم دائرة أو شكل بيضاوي دقيق',
    actionId: 'canvas:add-element',
    payload: { type: 'circle' },
    keywords: ['circle', 'دائرة', 'بيضاوي'],
  },
  {
    id: 'tool-shape-diamond',
    titleAr: 'معين / قرار مخطط',
    titleEn: 'Diamond',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'Diamond',
    descriptionAr: 'شكل معين للمخططات الانسيابية ونقاط اتخاذ القرار',
    actionId: 'canvas:add-element',
    payload: { type: 'diamond' },
    keywords: ['diamond', 'معين', 'قرار', 'مخطط'],
  },
  {
    id: 'tool-shape-triangle',
    titleAr: 'مثلث متساوي الأضلاع',
    titleEn: 'Triangle',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'Triangle',
    descriptionAr: 'رسم مثلث متجهي متناسق',
    actionId: 'canvas:add-element',
    payload: { type: 'triangle' },
    keywords: ['triangle', 'مثلث'],
  },
  {
    id: 'tool-shape-star',
    titleAr: 'نجمة خماسية',
    titleEn: 'Star',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'Star',
    descriptionAr: 'رسم نجمة تقييم أو تمييز هندسية',
    actionId: 'canvas:add-element',
    payload: { type: 'star' },
    keywords: ['star', 'نجمة', 'تقييم'],
  },
  {
    id: 'tool-shape-hexagon',
    titleAr: 'شكل سداسي (Hexagon)',
    titleEn: 'Hexagon',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'Hexagon',
    descriptionAr: 'خلية سداسية للمخططات التقنية',
    actionId: 'canvas:add-element',
    payload: { type: 'hexagon' },
    keywords: ['hexagon', 'سداسي'],
  },
  {
    id: 'tool-shape-connector',
    titleAr: 'موصل ذكي / سهم اتجاهي',
    titleEn: 'Smart Connector',
    category: 'vector-shapes',
    categoryAr: 'الأشكال الفيكتورية',
    iconName: 'ArrowRight',
    descriptionAr: 'سهم ذكي يربط بين العقد والكتل تلقائياً',
    actionId: 'canvas:add-element',
    payload: { type: 'connector' },
    keywords: ['connector', 'سهم', 'موصل', 'رابط'],
  },

  // 4. Diagrams, Math & Mindmaps
  {
    id: 'tool-diagram-node',
    titleAr: 'عقدة مخطط انسيابي',
    titleEn: 'Diagram Node',
    category: 'diagrams-math',
    categoryAr: 'المخططات والرياضيات',
    iconName: 'Sliders',
    descriptionAr: 'إدراج عقدة معالجة أو بداية أو نهاية',
    actionId: 'canvas:add-element',
    payload: { type: 'diagram-node' },
    keywords: ['diagram', 'مخطط', 'عقدة', 'انسيابي'],
  },
  {
    id: 'tool-mindmap-branch',
    titleAr: 'فرع خريطة ذهنية',
    titleEn: 'Mind Map Branch',
    category: 'diagrams-math',
    categoryAr: 'المخططات والرياضيات',
    iconName: 'GitBranch',
    descriptionAr: 'إدراج فرع تفكير متفرع ومرتبط بالفأرة',
    actionId: 'canvas:add-element',
    payload: { type: 'mindmap-node' },
    keywords: ['mindmap', 'خريطة ذهنية', 'تفكير', 'فرع'],
  },
  {
    id: 'tool-math-latex',
    titleAr: 'معادلة رياضية (LaTeX Engine)',
    titleEn: 'LaTeX Math Equation',
    category: 'latex-scientific',
    categoryAr: 'الرموز والمعادلات الرياضية (LaTeX)',
    iconName: 'Sigma',
    descriptionAr: 'كتابة وتصيير المعادلات الرياضية والرموز العلمية',
    actionId: 'canvas:add-element',
    payload: { type: 'latex-equation' },
    keywords: ['latex', 'math', 'معادلة', 'رياضيات', 'رموز', 'صيغة'],
  },
  {
    id: 'tool-latex-symbols-palette',
    titleAr: 'لوحة الرموز الإغريقية والعلمية',
    titleEn: 'Greek & Math Symbols',
    category: 'latex-scientific',
    categoryAr: 'الرموز والمعادلات الرياضية (LaTeX)',
    iconName: 'Sparkles',
    descriptionAr: 'إدراج الرموز الإغريقية والمؤثرات بنقرة فأرة واحدة',
    actionId: 'latex:insert-symbol',
    payload: { symbol: '\\alpha' },
    keywords: ['latex', 'greek', 'رموز', 'إغريقية', 'ألفا', 'بيتا', 'باي'],
  },
  {
    id: 'tool-latex-formula-presets',
    titleAr: 'قوالب الصيغ والمعادلات الجاهزة',
    titleEn: 'Formula Presets',
    category: 'latex-scientific',
    categoryAr: 'الرموز والمعادلات الرياضية (LaTeX)',
    iconName: 'Code2',
    descriptionAr: 'إدراج معادلات فيثاغورس، أينشتاين، والدستور التربيعي فورياً',
    actionId: 'latex:insert-preset',
    payload: { presetId: 'f-pythagoras' },
    keywords: ['formula', 'صيغة', 'معادلة', 'فيثاغورس', 'تربيعية', 'تكامل'],
  },
  {
    id: 'tool-latex-fractions-roots',
    titleAr: 'الكسور والجذور (Fractions & Roots)',
    titleEn: 'Fractions & Roots',
    category: 'latex-scientific',
    categoryAr: 'الرموز والمعادلات الرياضية (LaTeX)',
    iconName: 'Sliders',
    descriptionAr: 'هياكل الكسور الكسرية والجذور النونية',
    actionId: 'latex:insert-structure',
    payload: { latex: '\\frac{a}{b}' },
    keywords: ['fraction', 'root', 'كسر', 'جذر', 'بسط', 'مقام'],
  },
  {
    id: 'tool-latex-matrices',
    titleAr: 'المحددات والمصفوفات (Matrices)',
    titleEn: 'Matrix & Determinants',
    category: 'latex-scientific',
    categoryAr: 'الرموز والمعادلات الرياضية (LaTeX)',
    iconName: 'Grid',
    descriptionAr: 'مصفوفات ومحددات مخصصة بصفوف وأعمدة متناسقة',
    actionId: 'latex:insert-matrix',
    payload: { latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}' },
    keywords: ['matrix', 'مصفوفة', 'محدد', 'جبر خطي'],
  },
  {
    id: 'tool-latex-calculators',
    titleAr: 'المحسب الآلي والإحصائي',
    titleEn: 'Arithmetic Calculators',
    category: 'latex-scientific',
    categoryAr: 'الرموز والمعادلات الرياضية (LaTeX)',
    iconName: 'Sparkles',
    descriptionAr: 'حساب المجموع، المتوسط، التباين، ومعادلات الدرجة الثانية آلياً',
    actionId: 'latex:run-calc',
    payload: { calcId: 'calc-sum' },
    keywords: ['calc', 'حساب', 'مجموع', 'متوسط', 'إحصاء'],
  },

  // 5. Media & Explanations (الشروحات والملاحظات)
  {
    id: 'tool-callout-box',
    titleAr: 'مربع شرح تفاعلي (Callout Box)',
    titleEn: 'Callout Explainer',
    category: 'media-callouts',
    categoryAr: 'الشروحات والملاحظات',
    iconName: 'MessageSquare',
    descriptionAr: 'صندوق شرح إرشادي مع مؤشر اتجاهي للأزرار',
    actionId: 'canvas:add-element',
    payload: { type: 'callout-balloon' },
    keywords: ['callout', 'شرح', 'ملاحظة', 'توجيه'],
  },
  {
    id: 'tool-step-badge',
    titleAr: 'شارة رقم خطوة إجرائية',
    titleEn: 'Step Number Badge',
    category: 'media-callouts',
    categoryAr: 'الشروحات والملاحظات',
    iconName: 'CheckCircle2',
    descriptionAr: 'ترقيم متسلسل للخطوات التدريبية والشروحات',
    actionId: 'canvas:add-element',
    payload: { type: 'step-badge' },
    keywords: ['step', 'خطوة', 'ترقيم', 'تسلسل'],
  },
  {
    id: 'tool-spotlight-pin',
    titleAr: 'دبوس شرح تفاعلي (Spotlight Pin)',
    titleEn: 'Interactive Pin',
    category: 'media-callouts',
    categoryAr: 'الشروحات والملاحظات',
    iconName: 'Sparkles',
    descriptionAr: 'دبوس ينبثق منه شرح عند النقر عليه بالفأرة',
    actionId: 'canvas:add-element',
    payload: { type: 'spotlight-pin' },
    keywords: ['pin', 'دبوس', 'تفاعل', 'نقطة'],
  },

  // 6. History, Snapshots & Edit Actions
  {
    id: 'tool-edit-undo',
    titleAr: 'تراجع (Undo)',
    titleEn: 'Undo',
    category: 'history-edit',
    categoryAr: 'التحرير والتاريخ',
    iconName: 'Undo2',
    shortcut: 'Ctrl+Z',
    descriptionAr: 'التراجع عن آخر إجراء (لقطات الحالة)',
    actionId: 'history:undo',
    keywords: ['undo', 'تراجع', 'سابق'],
  },
  {
    id: 'tool-edit-redo',
    titleAr: 'إعادة (Redo)',
    titleEn: 'Redo',
    category: 'history-edit',
    categoryAr: 'التحرير والتاريخ',
    iconName: 'Redo2',
    shortcut: 'Ctrl+Y',
    descriptionAr: 'إعادة تطبيق الإجراء المتراجع عنه',
    actionId: 'history:redo',
    keywords: ['redo', 'إعادة', 'لاحق'],
  },
  {
    id: 'tool-edit-duplicate',
    titleAr: 'تكرار العنصر المختار',
    titleEn: 'Duplicate Element',
    category: 'history-edit',
    categoryAr: 'التحرير والتاريخ',
    iconName: 'Copy',
    shortcut: 'Ctrl+D',
    descriptionAr: 'استنساخ العنصر أو الكتلة فورياً بنقرة واحدة',
    actionId: 'element:duplicate',
    keywords: ['duplicate', 'نسخ', 'تكرار'],
  },
  {
    id: 'tool-edit-delete',
    titleAr: 'حذف العنصر',
    titleEn: 'Delete Element',
    category: 'history-edit',
    categoryAr: 'التحرير والتاريخ',
    iconName: 'Trash2',
    shortcut: 'Delete',
    descriptionAr: 'حذف العنصر المحدد من اللوحة',
    actionId: 'element:delete',
    keywords: ['delete', 'حذف', 'إزالة'],
  },

  // 7. Viewport & Breakpoints (العرض ونقاط التوقف)
  {
    id: 'tool-viewport-desktop',
    titleAr: 'عرض حاسوب مكتبي (1280px)',
    titleEn: 'Desktop View (1280px)',
    category: 'viewport-view',
    categoryAr: 'العرض والمعاينة',
    iconName: 'Monitor',
    descriptionAr: 'معاينة التصميم على شاشات العرض الكبيرة',
    actionId: 'viewport:breakpoint',
    payload: { breakpoint: 'desktop', width: 1280 },
    keywords: ['desktop', 'كمبيوتر', 'مكتبي', 'شاشة'],
  },
  {
    id: 'tool-viewport-tablet',
    titleAr: 'عرض جهاز لوحي (768px)',
    titleEn: 'Tablet View (768px)',
    category: 'viewport-view',
    categoryAr: 'العرض والمعاينة',
    iconName: 'Tablet',
    descriptionAr: 'معاينة تجاوب التصميم مع الأجهزة اللوحية',
    actionId: 'viewport:breakpoint',
    payload: { breakpoint: 'tablet', width: 768 },
    keywords: ['tablet', 'لوحي', 'تابلت'],
  },
  {
    id: 'tool-viewport-mobile',
    titleAr: 'عرض جوال ذكي (375px)',
    titleEn: 'Mobile View (375px)',
    category: 'viewport-view',
    categoryAr: 'العرض والمعاينة',
    iconName: 'Smartphone',
    descriptionAr: 'معاينة التجاوب مع شاشات الجوال الضيقة',
    actionId: 'viewport:breakpoint',
    payload: { breakpoint: 'mobile', width: 375 },
    keywords: ['mobile', 'جوال', 'هاتف'],
  },
  {
    id: 'tool-viewport-zoom-in',
    titleAr: 'تكبير الرؤية (Zoom In)',
    titleEn: 'Zoom In',
    category: 'viewport-view',
    categoryAr: 'العرض والمعاينة',
    iconName: 'ZoomIn',
    shortcut: 'Ctrl++',
    descriptionAr: 'تكبير مساحة العمل',
    actionId: 'viewport:zoom-in',
    keywords: ['zoom', 'تكبير', 'تقريب'],
  },
  {
    id: 'tool-viewport-zoom-out',
    titleAr: 'تصغير الرؤية (Zoom Out)',
    titleEn: 'Zoom Out',
    category: 'viewport-view',
    categoryAr: 'العرض والمعاينة',
    iconName: 'ZoomOut',
    shortcut: 'Ctrl+-',
    descriptionAr: 'تصغير مساحة العمل لرؤية شاملة',
    actionId: 'viewport:zoom-out',
    keywords: ['zoom', 'تصغير', 'إبعاد'],
  },
  // 10. Computational Notebook & Unit Engine Suite
  {
    id: 'tool-calc-scratchpad',
    titleAr: 'المفكرة الحسابية والمتغيرات',
    titleEn: 'Computational Scratchpad',
    category: 'computational-calc',
    categoryAr: 'الحسابات والمعادلات',
    iconName: 'Calculator',
    shortcut: 'Ctrl+Shift+C',
    descriptionAr: 'فتح المفكرة الحسابية وإدارة المتغيرات والاشتقاق النقي',
    actionId: 'dialog:computational-scratchpad',
    payload: { initialTab: 'variables' },
    keywords: ['calculator', 'scratchpad', 'حاسبة', 'متغيرات', 'معادلات', 'حساب'],
  },
  {
    id: 'tool-calc-magic-notes',
    titleAr: 'الملاحظات السحرية والتقييم اللحظي',
    titleEn: 'Magic Notes Live Evaluator',
    category: 'computational-calc',
    categoryAr: 'الحسابات والمعادلات',
    iconName: 'Sparkles',
    shortcut: 'Ctrl+Shift+M',
    descriptionAr: 'تقييم المعادلات التلقائي عند كتابة = وحساب المجموع الصاعد',
    actionId: 'dialog:computational-scratchpad',
    payload: { initialTab: 'magic-notes' },
    keywords: ['magic', 'notes', 'سحرية', 'ملاحظات', 'حساب فوري', 'مجموع'],
  },
  {
    id: 'tool-calc-unit-converter',
    titleAr: 'محول الوحدات والأوقات',
    titleEn: 'Unit & Time Converter',
    category: 'computational-calc',
    categoryAr: 'الحسابات والمعادلات',
    iconName: 'Ruler',
    shortcut: 'Ctrl+Shift+U',
    descriptionAr: 'تحويل الأطوال، الأوزان، الأوقات، والحرارة بصفر اعتماديات',
    actionId: 'dialog:computational-scratchpad',
    payload: { initialTab: 'unit-converter' },
    keywords: ['units', 'converter', 'تحويل', 'وحدات', 'أطوال', 'أوقات'],
  },
  {
    id: 'tool-calc-test-suite',
    titleAr: 'مختبر اختبارات التحكم السلبية',
    titleEn: 'Negative Control Test Suite',
    category: 'computational-calc',
    categoryAr: 'الحسابات والمعادلات',
    iconName: 'CheckCircle2',
    descriptionAr: 'تشغيل 15 فحصاً معمارياً دقيقاً للتحقق من سلامة النواة',
    actionId: 'dialog:computational-scratchpad',
    payload: { initialTab: 'tests' },
    keywords: ['tests', 'negative control', 'اختبارات', 'فحص', 'تحقق'],
  },
  // 11. Motion, Pen Curves & Advanced Document Tools (New Code_X3 Suite)
  {
    id: 'tool-motion-path',
    titleAr: 'محرر مسار الحركة الحلقي',
    titleEn: 'Motion Path Editor',
    category: 'vector-shapes',
    categoryAr: 'الأشكال والمسارات المتجهة',
    iconName: 'Route',
    descriptionAr: 'تعديل مسارات الحركة بنقاط التثبيت ومقابض بيزير ومحاكاة الدوران الحية',
    actionId: 'tool:motion-path',
    keywords: ['motion', 'path', 'animation', 'حركة', 'مسار', 'أنيميشن', 'بيزير'],
  },
  {
    id: 'tool-pen-bezier',
    titleAr: 'أداة القلم ومنحنيات بيزير',
    titleEn: 'Pen & Bezier Curve Tool',
    category: 'vector-shapes',
    categoryAr: 'الأشكال والمسارات المتجهة',
    iconName: 'PenTool',
    shortcut: 'P',
    descriptionAr: 'رسم وتعديل المنحنيات الدقيقة وتقسيم الشرائح بنقاط التثبيت والمقابض المتناظرة',
    actionId: 'tool:bezier-pen',
    keywords: ['pen', 'bezier', 'curve', 'قلم', 'منحنى', 'فيكتور', 'بيزير'],
  },
  {
    id: 'tool-find-replace',
    titleAr: 'البحث والاستبدال الشامل',
    titleEn: 'Universal Find & Replace',
    category: 'history-edit',
    categoryAr: 'التاريخ والتحرير',
    iconName: 'Search',
    shortcut: 'Ctrl+F',
    descriptionAr: 'البحث المتقدم والاستبدال الفردي والجماعي عبر عناصر الكانفا والمستندات',
    actionId: 'dialog:find-replace',
    keywords: ['find', 'replace', 'search', 'بحث', 'استبدال', 'تغيير'],
  },
  {
    id: 'tool-dynamic-fields',
    titleAr: 'إدراج الحقول الديناميكية',
    titleEn: 'Dynamic Fields Inserter',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'Sparkles',
    shortcut: 'Ctrl+Shift+D',
    descriptionAr: 'إدراج حقول التاريخ، الوقت، ترقيم الصفحات، وبيانات المستند اللحظية',
    actionId: 'dialog:dynamic-fields',
    keywords: ['dynamic', 'fields', 'date', 'page', 'حقول', 'تاريخ', 'صفحة', 'ديناميكي'],
  },
  {
    id: 'tool-comments-thread',
    titleAr: 'الملاحظات والتعليقات التعاونية',
    titleEn: 'Collaborative Comments',
    category: 'media-callouts',
    categoryAr: 'الوسائط والملاحظات',
    iconName: 'MessageSquare',
    shortcut: 'Ctrl+Shift+K',
    descriptionAr: 'إضافة دبابيس وسلاسل تعليقات تفاعلية وملاحظات مراجعة للمستند',
    actionId: 'drawer:comments',
    keywords: ['comments', 'notes', 'threads', 'تعليقات', 'ملاحظات', 'دبابيس', 'مراجعة'],
  },
  {
    id: 'tool-system-doctor',
    titleAr: 'دكتور النظام والإصلاح والحاسبة',
    titleEn: 'System Doctor & Self-Healing Engine',
    category: 'computational-calc',
    categoryAr: 'الحسابات والمعادلات',
    iconName: 'Stethoscope',
    shortcut: 'Ctrl+Shift+H',
    descriptionAr: 'اكتشاف المكونات، معالجة الأخطاء ذاتياً، وفحص الخوارزميات والحاسبة الهندسية المدمجة',
    actionId: 'dialog:system-doctor',
    keywords: ['doctor', 'healing', 'diagnostic', 'calculator', 'دكتور', 'إصلاح', 'حاسبة', 'تشخيص', 'خوارزميات'],
  },
  {
    id: 'tool-master-dev-studio',
    titleAr: 'استوديو المطور الرئيسي الاستثنائي',
    titleEn: 'Master Omnipotent DevStudio',
    category: 'developer',
    categoryAr: 'بيئة وأدوات المطور',
    iconName: 'Terminal',
    shortcut: 'Ctrl+Shift+Alt+D',
    descriptionAr: 'اللوحة الأم للمطور: إدارة شجرة المشروع، مشغل المهام، دكتور الجودة، والحاسبة الهندسية',
    actionId: 'dialog:dev-studio',
    keywords: ['dev', 'studio', 'developer', 'scaffolding', 'tree', 'rollback', 'مطور', 'استوديو', 'شجرة', 'مهام'],
  },
  {
    id: 'tool-line-connector',
    titleAr: 'تحرير الخطوط والموصّلات المباشر',
    titleEn: 'Line & Connector Editor',
    category: 'vector-shapes',
    categoryAr: 'الأشكال والمسارات المتجهة',
    iconName: 'GitBranch',
    descriptionAr: 'مقابض نقاط نهاية الخطوط والمنحنيات والموصّلات مع إعادة توجيه تلقائية للوصلات',
    actionId: 'tool:line-connector',
    keywords: ['line', 'connector', 'endpoint', 'anchor', 'خط', 'موصل', 'نقطة نهاية', 'مسار'],
  },
  {
    id: 'tool-tag-aware-replace',
    titleAr: 'استبدال واعٍ بوسوم HTML',
    titleEn: 'Tag-Aware Find & Replace',
    category: 'history-edit',
    categoryAr: 'التاريخ والتحرير',
    iconName: 'Replace',
    shortcut: 'Ctrl+Alt+F',
    descriptionAr: 'عدّ واستبدال يمران على فقرات النص فقط ويتجاهلان الوسوم والخصائص — عدٌّ يطابق الاستبدال دائماً',
    actionId: 'dialog:tag-aware-replace',
    keywords: ['tags', 'html', 'outside', 'وسوم', 'استبدال', 'نص', 'عد'],
  },
  {
    id: 'tool-asset-interner',
    titleAr: 'إدارة الأصول بعنونة المحتوى',
    titleEn: 'Content-Addressed Assets',
    category: 'media-callouts',
    categoryAr: 'الوسائط والملاحظات',
    iconName: 'ImageIcon',
    descriptionAr: 'تضمين صور بتجزئة المحتوى وتقليل حجمها تلقائياً مع عرض الأصول اليتيمة ووزن المستند',
    actionId: 'dialog:asset-interner',
    keywords: ['assets', 'images', 'dedupe', 'sha256', 'assets', 'صور', 'أصول', 'تجزئة', 'تصغير'],
  },
  {
    id: 'tool-obsidian-import',
    titleAr: 'استيراد خزنة Obsidian',
    titleEn: 'Obsidian Vault Importer',
    category: 'document-io',
    categoryAr: 'استيراد وتصدير المستندات',
    iconName: 'FolderOpen',
    descriptionAr: 'تحويل ملفات Markdown إلى صفحات مساحة مع حل روابط [[wikilinks]] وبناء شجرة المجلدات',
    actionId: 'dialog:obsidian-import',
    keywords: ['obsidian', 'vault', 'markdown', 'import', 'wikilinks', 'خزنة', 'استيراد', 'ماركداون'],
  },
  {
    id: 'tool-schema-fields',
    titleAr: 'الحقول المكتوبة القائمة على المخطط',
    titleEn: 'Typed Schema Fields',
    category: 'flow-elements',
    categoryAr: 'عناصر الويب والتدفق',
    iconName: 'ListFilter',
    descriptionAr: 'مخطط الحقول وحقول المسائل (Status, Assignee, Priority) مع فلاتر الرؤية وترتيب اللوحة',
    actionId: 'dialog:schema-fields',
    keywords: ['fields', 'schema', 'issues', 'tracker', 'board', 'حقول', 'مخطط', 'مسائل', 'لوحة'],
  },
  {
    id: 'tool-plan-apply-agent',
    titleAr: 'سطح الوكيل (فحص وتخطيط وتطبيق)',
    titleEn: 'Agent PLAN/APPLY Surface',
    category: 'developer',
    categoryAr: 'بيئة وأدوات المطور',
    iconName: 'ShieldAlert',
    descriptionAr: 'فحص المستند، مخطط كلي وإحصائياته، وأفعال كتابة آمنة بخطوة تراجع واحدة مع أخطاء صامتة مكشوفة',
    actionId: 'dialog:plan-apply-agent',
    keywords: ['agent', 'validate', 'plan', 'apply', 'findings', 'وكيل', 'فحص', 'تخطيط', 'تطبيق'],
  },

  // 12. New Code_X3 Editor Tool Suite (أدوات مجلد editor المدمجة في النواة المشتركة)
  {
    id: 'tool-comment-pin',
    titleAr: 'أداة دبوس التعليق التفاعلي',
    titleEn: 'Interactive Comment Pin Tool',
    category: 'media-callouts',
    categoryAr: 'الشروحات والملاحظات',
    iconName: 'MessageSquare',
    shortcut: 'C',
    descriptionAr: 'وضع دبوس تعليق مرتبط بعنصر أو نقطة أو الشريحة — بتثبيت ذكي يختار الوضع الأنسب (عنصر/نقطة/شريحة)',
    actionId: 'tool:comment-pin',
    keywords: ['comment', 'pin', 'thread', 'annotate', 'تعليق', 'دبوس', 'ملاحظة', 'مراجعة', 'تثبيت'],
  },
  {
    id: 'tool-connector-reroute',
    titleAr: 'إعادة توجيه الموصلات التلقائية',
    titleEn: 'Automatic Connector Rerouting',
    category: 'vector-shapes',
    categoryAr: 'الأشكال والمسارات المتجهة',
    iconName: 'GitBranch',
    descriptionAr: 'إعادة توجيه الموصلات المرساة تلقائياً كلما تحركت العناصر — تثبيت على الجانب الصريح أو أقرب حد وتنظيف المراسي الميتة',
    actionId: 'tool:connector-reroute',
    keywords: ['connector', 'reroute', 'anchor', 'link', 'موصل', 'إعادة توجيه', 'مرساة', 'ربط', 'حدود'],
  },
  {
    id: 'tool-bezier-split',
    titleAr: 'تقسيم الشرائح على المنحنى',
    titleEn: 'On-Curve Bezier Segment Split',
    category: 'vector-shapes',
    categoryAr: 'الأشكال والمسارات المتجهة',
    iconName: 'Spline',
    descriptionAr: 'إدراج نقطة تثبيت على أي شريحة بيزير بضغطة مزدوجة — تقسيم De Casteljau يحافظ على الشكل تماماً',
    actionId: 'tool:bezier-split',
    keywords: ['bezier', 'split', 'insert', 'segment', 'curve', 'بيزير', 'تقسيم', 'إدراج', 'شريحة', 'منحنى'],
  },
  {
    id: 'tool-motion-speeds',
    titleAr: 'نقاط التثبيت الهجينة والسرعات',
    titleEn: 'Hybrid Waypoints & Speeds',
    category: 'vector-shapes',
    categoryAr: 'الأشكال والمسارات المتجهة',
    iconName: 'Route',
    descriptionAr: 'تمليس AUTO تلقائي (Catmull-Rom) أو تحكم MANUAL دقيق لكل نقطة مسار حركة مع مضاعفات سرعة (0.2–4×)',
    actionId: 'tool:motion-speeds',
    keywords: ['motion', 'path', 'waypoint', 'speed', 'auto', 'manual', 'حركة', 'مسار', 'نقطة تثبيت', 'سرعة', 'هجين'],
  },
  {
    id: 'tool-clip-payload',
    titleAr: 'حمولة القصاصات الذكية (عناصر وشرائح)',
    titleEn: 'Smart Clip Payload (Elements & Slides)',
    category: 'media-callouts',
    categoryAr: 'الشروحات والملاحظات',
    iconName: 'ClipboardCopy',
    shortcut: 'V',
    descriptionAr: 'تسلسل العناصر/الشرائح مع أصولها وخطوطها في حمولة JSON مُعلّمة، وإعادة بناء غير الموثوق عند اللصق مع إعادة ترميز الأصول المتصادمة',
    actionId: 'tool:clip-payload',
    keywords: ['clipboard', 'copy', 'paste', 'payload', 'serialize', 'assets', 'fonts', 'قصاصة', 'نسخ', 'لصق', 'أصول', 'خطوط', 'تسلسل'],
  },
  {
    id: 'tool-color-alpha',
    titleAr: 'دمج الشفافية اللونية',
    titleEn: 'Color Alpha Combiner',
    category: 'media-callouts',
    categoryAr: 'الشروحات والملاحظات',
    iconName: 'Droplet',
    shortcut: 'A',
    descriptionAr: 'تحويل {hex, alpha} إلى أقصر CSS صالح يحفظ الشفافية (rgba بثلاث خانات) — لأدوات التعبئة والحدود والتدرجات في لوحات الخصائص',
    actionId: 'tool:color-alpha',
    keywords: ['color', 'alpha', 'rgba', 'opacity', 'hex', 'combine', 'لون', 'شفافية', 'تعبئة', 'حدود', 'دمج'],
  },
  {
    id: 'tool-dialog-code-studio',
    titleAr: 'استوديو الكود التفاعلي المتقدم (WYSIWYG Code Studio)',
    titleEn: 'Interactive WYSIWYG Code Studio',
    category: 'developer',
    categoryAr: 'الأدوات المتقدمة والبرمجة',
    iconName: 'Code2',
    shortcut: 'Ctrl+Shift+C',
    descriptionAr: 'محرر ومفسر كود حي يدعم 10 لغات مع معاينة فورية ومخططات بيانية تفاعلية',
    actionId: 'dialog:code-studio',
    keywords: ['code', 'studio', 'wysiwyg', 'html', 'json', 'chart', 'كود', 'محرر', 'برمجة', 'معاينة'],
  },
  {
    id: 'tool-dialog-image-editor',
    titleAr: 'محرر ومعالج الصور والفلاتر المتقدم',
    titleEn: 'Advanced Image & Filter Studio',
    category: 'media-callouts',
    categoryAr: 'الوسائط ومعالجة الصور',
    iconName: 'ImageIcon',
    descriptionAr: 'استوديو شامل لقص الصور، تطبيق الفلاتر الرياضية، منحنيات الألوان، وضبط المستويات',
    actionId: 'dialog:image-editor',
    keywords: ['image', 'photo', 'crop', 'filter', 'curves', 'صورة', 'قص', 'فلاتر', 'معالجة', 'هيستوغرام'],
  },
  {
    id: 'tool-dialog-templates',
    titleAr: 'مكتبة نماذج التصميم والشروحات التفاعلية',
    titleEn: 'Advanced Design & Annotation Templates',
    category: 'media-callouts',
    categoryAr: 'القوالب والشروحات',
    iconName: 'Layout',
    shortcut: 'T',
    descriptionAr: 'مكتبة تضم أكثر من 15 قالباً عصرياً للشروحات، الموصلات الذكية، ودبابيس الخطوات التفاعلية',
    actionId: 'dialog:templates',
    keywords: ['template', 'callout', 'connector', 'walkthrough', 'قوالب', 'نماذج', 'شروحات', 'موصلات'],
  },
  {
    id: 'tool-dialog-callouts',
    titleAr: 'مربعات الشرح والملاحظات العائمة',
    titleEn: 'Interactive Callouts & Badges',
    category: 'media-callouts',
    categoryAr: 'الشروحات والملاحظات',
    iconName: 'MessageSquare',
    descriptionAr: 'إدراج مربعات شرح وملاحظات تفاعلية متعددة الرؤوس وشارات التوثيق',
    actionId: 'dialog:callouts',
    keywords: ['callout', 'badge', 'note', 'شرح', 'ملاحظة', 'شارة', 'توثيق'],
  },
  {
    id: 'tool-dialog-split-layouts',
    titleAr: 'قوالب التقسيم الذكي والتفاعل اللحظي (Smart Split Layouts)',
    titleEn: 'Smart Split Layouts & Real-Time Panes',
    category: 'media-callouts',
    categoryAr: 'التقسيم الذكي والتفاعل اللحظي',
    iconName: 'Columns',
    shortcut: 'Ctrl+Shift+S',
    descriptionAr: 'قوالب تقسيم الصفحة الذكية (50/50 مقارنة، كود ومعاينة حية، تقسيم ثلاثي، شبكة رباعية)',
    actionId: 'canvas:add-element',
    payload: { type: 'template', templateId: 'split-two-pane-comparison' },
    keywords: ['split', 'pane', 'layout', 'comparison', 'live', 'تقسيم', 'مقارنة', 'ذكية', 'تفاعل', 'نوافذ'],
  },
  {
    id: 'tool-dialog-dashboards',
    titleAr: 'لوحات العمل والمقارنات التفاعلية (Multi-Zone Dashboards)',
    titleEn: 'Multi-Zone Interactive Dashboards',
    category: 'media-callouts',
    categoryAr: 'لوحات العمل والمقارنات',
    iconName: 'LayoutGrid',
    descriptionAr: 'قوالب لوحات العمل متعددة الأجنحة والمناطق مع مؤشرات أداء KPI حية وتزامن تلقائي',
    actionId: 'canvas:add-element',
    payload: { type: 'template', templateId: 'split-three-column-dashboard' },
    keywords: ['dashboard', 'kpi', 'chart', 'grid', 'لوحة', 'مؤشرات', 'مقارنات', 'تحكم'],
  },
];
